import ssl
import csv
import os
import smtplib
import ssl, os
#from dotenv import load_dotenv

#load_dotenv()

from_address = os.getenv('SENDER')
password = os.getenv('PSWD')

SUBJECT = "[C&S] Dep Selection"
BODY = """
Hello coder;

Welcome {name} to code and share;
We're happy to inform you that you're selected in the {department} department;

Cordially;

NB: This is an automated email generated by python !!
            <<<< SORRY FOR THE SPAM >>>>
"""

message = 'Subject: {}\n\n{}'.format(SUBJECT, BODY)

# Creating a connection to SMTP server for gmail
port = 587  # For TLS

with smtplib.SMTP("smtp.gmail.com", port) as server:
    server.starttls()
    server.login(from_address, password)
    #server.set_debuglevel(1)

    with open("contact.csv") as file:
        reader = csv.reader(file)       # returns a list [.. , .. , ..]
        next(reader)  # Skip header row
        for row in reader:
            assert len(row) == 3, f'Expected 3 columns but only have {len(row)}: {row}'
            name, email, dep = row
            server.sendmail(from_address, to_addrs=email,
                            msg=message.format(name=name, department=dep))

    server.quit()
    
print("Emails successfully sent")